name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/Lamp, examples/LampDimmer, examples/Switch , examples/TempSensor]

    steps:

    - name: Step 1 - Checkout Repo
      uses: actions/checkout@v2
    - name: Step 2 - Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Step 3 - Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Step 4 - Set up Python
      uses: actions/setup-python@v2
    - name: Step 5 - Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Step 6 - Run build examples using PlatformIO
      run: pio ci --lib="." -b uno -b leonardo -b nano_33_iot
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
